server:
  port: 8888
spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-self-service
          predicates:
            - Path=/pms/**
        - id: ums-route
          uri: lb://ums-self-service
          predicates:
            - Path=/pums/**
        - id: wms-route
          uri: lb://wms-self-service
          predicates:
            - Path=/wms/**
        - id: sms-route
          uri: lb://sms-self-service
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://oms-self-service
          predicates:
            - Path=/oms/**